Build RISC-V engine, RISC-V gen_snapshots (#24)
* add risc-v patches
* don't use default linux sysroot for riscv64
* add risc-v to build matrix
* cross-compile risc-v gen_snapshot
* install gcc-riscv64-linux-gnu cross toolchain, build risc-v binaries using that
* apply abseil risc-v patches
* fix windows -> linux riscv64 gen_snapshot build
* fix quoting when checking stable/beta tag
* fix channel resolving for PRs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -73,15 +73,22 @@ jobs:
           STABLE_REF="$(git tag --points-at HEAD 'flutter/stable/*' | cut -f1 | cut -d/ -f3)"
           BETA_REF="$(git tag --points-at HEAD 'flutter/beta/*' | cut -f1 | cut -d/ -f3)"
           
-          if test -n $STABLE_REF; then
+          if test -n "$STABLE_REF"; then
             echo "is-stable=true" >> $GITHUB_OUTPUT
             echo "is-beta=false" >> $GITHUB_OUTPUT
             echo "first-semver=$STABLE_REF" >> $GITHUB_OUTPUT
+            echo "channel=stable" >> $GITHUB_OUTPUT
             CHANNEL=stable
-          elif test -n $BETA_REF; then
+          elif test -n "$BETA_REF"; then
             echo "is-stable=false" >> $GITHUB_OUTPUT
             echo "is-beta=true" >> $GITHUB_OUTPUT
             echo "first-semver=$BETA_REF" >> $GITHUB_OUTPUT
+            echo "channel=beta" >> $GITHUB_OUTPUT
+            CHANNEL=beta
+          elif ${{ startsWith(github.ref, 'refs/pull') && 'true' || 'false' }}; then
+            echo "is-stable=false" >> $GITHUB_OUTPUT
+            echo "is-beta=true" >> $GITHUB_OUTPUT
+            echo "channel=beta" >> $GITHUB_OUTPUT
             CHANNEL=beta
           else
             echo "Could not determine channel."
@@ -93,7 +100,6 @@ jobs:
           ENGINE_HASH=$(cat flutter.version.$CHANNEL | tr -dc [:xdigit:])
 
           echo "engine-hash=$ENGINE_HASH" >> $GITHUB_OUTPUT
-
           
   populate-engine-src-cache:
     name: 'Prepopulate engine source cache'
@@ -296,9 +302,11 @@ jobs:
           echo build-arm-gen-snapshot: ${{ matrix.build-arm-gen-snapshot }}
           echo build-arm64-gen-snapshot: ${{ matrix.build-arm64-gen-snapshot }}
           echo build-x64-gen-snapshot: ${{ matrix.build-x64-gen-snapshot }}
+          echo build-riscv64-gen-snapshot: ${{ matrix.build-riscv64-gen-snapshot }}
           echo arm-gen-snapshot-path: ${{ matrix.arm-gen-snapshot-path }}
           echo arm64-gen-snapshot-path: ${{ matrix.arm64-gen-snapshot-path }}
           echo x64-gen-snapshot-path: ${{ matrix.x64-gen-snapshot-path }}
+          echo riscv64-gen-snapshot-path: ${{ matrix.riscv64-gen-snapshot-path }}
           
           echo build-universal: ${{ matrix.build-universal }}
 
@@ -310,6 +318,13 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y ninja-build
+
+          # The engine scripts don't provide a sysroot for RISC-V 64,
+          # so we rely on the headers/libs provided by the gcc-riscv64-linux-gnu
+          # cross toolchain.
+          if ${{ matrix.build-riscv64-gen-snapshot || (matrix.build-engine && matrix.cpu == 'riscv64') }}; then
+            sudo apt-get install -y gcc-riscv64-linux-gnu g++-riscv64-linux-gnu
+          fi
       
       - name: Install dependencies (MacOS)
         if: runner.os == 'macOS'
@@ -382,12 +397,27 @@ jobs:
 
             popd
           fi
+
+          if [ -d "$GITHUB_WORKSPACE_UNIX/abseil-patches" ]; then
+            pushd engine/src/flutter/third_party/abseil-cpp
+
+            git apply $GITHUB_WORKSPACE_UNIX/abseil-patches/*.patch
+            git status
+
+            popd
+          fi
       
       # This can't be done in the prepopulate step since on MacOS, it depends
       # on a buildroot patch.
+      #
+      # We actually don't need the sysroots to build the gen_snapshots,
+      # but configuring will fail if they're missing.
+      #
+      # That's why the RISC-V gen_snapshots build fine, even though it
+      # doesn't have a sysroot.
       - name: Download linux sysroot
         working-directory: flutter/engine/src/build/linux/sysroot_scripts
-        if: matrix.cpu && runner.os == 'macOS'
+        if: matrix.cpu && matrix.cpu != 'riscv64' && runner.os == 'macOS'
         timeout-minutes: 5
         run: |
           ./install-sysroot.py --arch=${{ matrix.cpu == 'x64' && 'amd64' || matrix.cpu }}
@@ -420,6 +450,7 @@ jobs:
             ${{ matrix.build-x64-gen-snapshot && matrix.x64-gen-snapshot-path || '' }} \
             ${{ matrix.build-arm-gen-snapshot && matrix.arm-gen-snapshot-path || '' }} \
             ${{ matrix.build-arm64-gen-snapshot && matrix.arm64-gen-snapshot-path || '' }} \
+            ${{ matrix.build-riscv64-gen-snapshot && matrix.riscv64-gen-snapshot-path || '' }} \
             ${{ matrix.build-universal && 'flutter_embedder.h icudtl.dat' || '' }}
 
       - name: Add flutter.version and dart-sdk.version file
@@ -496,6 +527,16 @@ jobs:
           
           tar -cJvf ../gen-snapshot-${{ runner.os }}-ARM64-${{ matrix.artifact-name }}-${{ matrix.flavor }}.tar.xz *
   
+      - name: Package riscv64 gen_snapshot
+        if: matrix.build-riscv64-gen-snapshot
+        run: |
+          mkdir -p pkg-riscv64-gen-snapshot
+
+          pushd pkg-riscv64-gen-snapshot
+          cp $BUILD_DIR/${{ matrix.riscv64-gen-snapshot-path }} $BUILD_DIR/compile_commands.json .
+
+          tar -cJvf ../gen-snapshot-${{ runner.os }}-RISCV64-${{ matrix.artifact-name }}-${{ matrix.flavor }}.tar.xz *
+      
       - name: Package universal artifacts
         if: matrix.build-universal
         run: |
@@ -553,6 +594,20 @@ jobs:
           name: gen-snapshot-${{ runner.os }}-ARM64-${{ matrix.artifact-name }}-${{ matrix.flavor }}-tar-xz
           path: gen-snapshot-${{ runner.os }}-ARM64-${{ matrix.artifact-name }}-${{ matrix.flavor }}.tar.xz
 
+      - name: Upload riscv64 gen_snapshot
+        if: matrix.build-riscv64-gen-snapshot
+        uses: actions/upload-artifact@v4
+        with:
+          name: gen-snapshot-${{ runner.os }}-RISCV64-${{ matrix.artifact-name }}-${{ matrix.flavor }}
+          path: pkg-riscv64-gen-snapshot/*
+      
+      - name: Upload riscv64 gen_snapshot (.tar.xz)
+        if: matrix.build-riscv64-gen-snapshot
+        uses: actions/upload-artifact@v4
+        with:
+          name: gen-snapshot-${{ runner.os }}-RISCV64-${{ matrix.artifact-name }}-${{ matrix.flavor }}-tar-xz
+          path: gen-snapshot-${{ runner.os }}-RISCV64-${{ matrix.artifact-name }}-${{ matrix.flavor }}.tar.xz
+      
       - name: Upload engine
         if: matrix.build-engine
         uses: actions/upload-artifact@v4
@@ -731,6 +786,7 @@ jobs:
           - pi3-64
           - pi4
           - pi4-64
+          - riscv64-generic
         flavor:
           - debug_unopt
           - debug
@@ -974,6 +1030,7 @@ jobs:
           # - armv7-generic
           - aarch64-generic
           # - x64-generic
+          - riscv64-generic
         flavor:
           - debug_unopt
           - debug
@@ -1091,7 +1148,7 @@ jobs:
           tag: engine_${{ needs.resolve-version.outputs.engine-hash }} --force
           tag_push: '--force'
           fetch: false
-          push: ${{ needs.resolve-version.outputs.is-stable }}
+          push: ${{ needs.resolve-version.outputs.is-stable && !startsWith(github.ref, 'refs/pull') }}
   
   release:
     name: 'Publish release'
@@ -1116,7 +1173,7 @@ jobs:
           tree -apugshDF
       
       - uses: softprops/action-gh-release@v1
-        if: ${{ needs.resolve-version.outputs.is-stable == 'true' || needs.resolve-version.outputs.is-beta == 'true' }}
+        if: ${{ needs.resolve-version.outputs.is-stable == 'true' || needs.resolve-version.outputs.is-beta == 'true'}}
         with:
           name: ${{ needs.resolve-version.outputs.semver }}
           body: |
@@ -1129,4 +1186,5 @@ jobs:
           files: |
             release-files/*
           prerelease: ${{ needs.resolve-version.outputs.is-stable != 'true' }}
+          draft: ${{ startsWith(github.ref, 'refs/pull') }}
 
